<a href="https://colab.research.google.com/github/chaudhary-dotcom/back-propagation/blob/main/BackPropagation_step_by_step-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import numpy as np
import pandas as pd

In [108]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [109]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [110]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [111]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [112]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b

  return Z

In [113]:
# forward prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    print('A'+str(l-1)+': ', A_prev)
    print('W'+str(l)+': ', Wl)
    print('b'+str(l)+': ', bl)
    print('--'*20)

    A = linear_forward(A_prev, Wl, bl)
    print('A'+str(l)+': ', A)
    print('**'*20)

  return A,A_prev

In [114]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) #Shape(no of features, no of trainig eXamples)
y = df[['lpa']].values[0][0]

# parameters initialiation
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [115]:
(y - 0.32)**2

np.float64(13.5424)

In [116]:
A1

array([[1.6],
       [1.6]])

In [117]:
y_hat = y_hat[0][0]
y_hat


np.float64(0.32000000000000006)

In [118]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [119]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1)
y=df[['lpa']].values[3][0]

y_hat, A1 = L_layer_forward(X,parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.7]
 [1.7]]
****************************************
A1:  [[1.7]
 [1.7]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.34]]
****************************************


In [120]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipython-input-1223655746.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
/tmp/ipython-input-1223655746.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
/tmp/ipython-input-1223655746.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0]+(0.001*2*(y-y_hat))

In [121]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0]+(0.001*2*(y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2*(y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['W1'][1][0] + (0.001*2*(y-y_hat)*parameters['W2'][1][0])

In [122]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y= df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.10740404],
        [0.10740404]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [123]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat =y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
parameters

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.10740404]
 [0.10740404]]
----------------------------------------
A1:  [[1.81270598]
 [1.81270598]]
****************************************
A1:  [[1.81270598]
 [1.81270598]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.52437005]]
****************************************


{'W1': array([[0.11460183, 0.11689338],
        [0.11460183, 0.11689338]]),
 'b1': array([[0.1157476],
        [0.1157476]]),
 'W2': array([[0.128002],
        [0.128002]]),
 'b2': array([[0.13695326]])}

In [124]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat =y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
parameters

A0:  [[7]
 [9]]
W1:  [[0.11460183 0.11689338]
 [0.11460183 0.11689338]]
b1:  [[0.1157476]
 [0.1157476]]
----------------------------------------
A1:  [[1.94937681]
 [1.98604174]]
****************************************
A1:  [[1.94937681]
 [1.98604174]]
W2:  [[0.128002]
 [0.128002]]
b2:  [[0.13695326]]
----------------------------------------
A2:  [[0.64069472]]
****************************************


{'W1': array([[0.12577358, 0.13125707],
        [0.12580307, 0.13129498]]),
 'b1': array([[0.12736954],
        [0.12740324]]),
 'W2': array([[0.14889661],
        [0.14928961]]),
 'b2': array([[0.16000822]])}

In [125]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat =y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
parameters

A0:  [[7]
 [9]]
W1:  [[0.12577358 0.13125707]
 [0.12580307 0.13129498]]
b1:  [[0.12736954]
 [0.12740324]]
----------------------------------------
A1:  [[2.14001219]
 [2.22785752]]
****************************************
A1:  [[2.14001219]
 [2.22785752]]
W2:  [[0.14889661]
 [0.14928961]]
b2:  [[0.16000822]]
----------------------------------------
A2:  [[0.81124477]]
****************************************


{'W1': array([[0.14096936, 0.15079449],
        [0.1411271 , 0.15099731]]),
 'b1': array([[0.14314018],
        [0.14331625]]),
 'W2': array([[0.17538464],
        [0.17686494]]),
 'b2': array([[0.18924245]])}

In [126]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
  Loss = []

  for j in range(df.shape[0]):
    X=df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    # parameters initialization

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epochs -', i+1, 'Loss - ', np.array(Loss).mean())
parameters


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.10740404]
 [0.10740404]]
----------------------------------------
A1:  [[1.81270598]
 [1.81270598]]
****************************************
A1:  [[1.81270598]
 [1.81270598]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.52437005]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11460183 0.11689338]
 [0.11460183 0.11689338]]
b1:  [[0.1157476]
 [0.1157476]]
----------------------------------------
A1:  [[1.94937681]
 [1.98604174]]
****************************************
A1:  [[1.94937681]
 [1.98604174]]
W2:  [[0.128002]
 [0.12800

{'W1': array([[0.25923594, 0.37733018],
        [0.2707293 , 0.39914494]]),
 'b1': array([[0.26060268],
        [0.27231684]]),
 'W2': array([[0.41241094],
        [0.47903871]]),
 'b2': array([[0.48235273]])}

# Using Keras

In [127]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [128]:
model = Sequential()

model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [129]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [130]:
model.get_weights()

[array([[-0.5339469 ,  0.64229596],
        [-0.4278497 ,  1.2230676 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.6545354],
        [-0.9099791]], dtype=float32),
 array([0.], dtype=float32)]

In [131]:
new_weights = [np.array([[0.1,0.1],
                         [0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],
                        [0.1]],dtype=np.float32),
               np.array([0.], dtype=np.float32)]



In [132]:
model.set_weights(new_weights)

In [133]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [134]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [135]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 31.8140  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.3405 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.5407 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.5670 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.5194 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.4262 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.4305 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.9857 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.5433 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.6060 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.3870 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.4389 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.4761 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.6324 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.9152
Epoch 16/75
4/4 ━━━

In [136]:
model.get_weights()

[array([[0.37380165, 0.37380165],
        [0.36555442, 0.36555442]], dtype=float32),
 array([0.27238485, 0.27238485], dtype=float32),
 array([[0.37297264],
        [0.37297264]], dtype=float32),
 array([0.20471519], dtype=float32)]